/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotRouteImport } from './routes/hot'
import { Route as SpiritRouteImport } from './routes/spirit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotRoute = HotRouteImport.update({
  id: '/hot',
  path: '/hot',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiritRoute = SpiritRouteImport.update({
  id: '/spirit',
  path: '/spirit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hot': typeof HotRoute
  '/spirit': typeof SpiritRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hot': typeof HotRoute
  '/spirit': typeof SpiritRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hot': typeof HotRoute
  '/spirit': typeof SpiritRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hot' | '/spirit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hot' | '/spirit'
  id: '__root__' | '/' | '/hot' | '/spirit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotRoute: typeof HotRoute
  SpiritRoute: typeof SpiritRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot': {
      id: '/hot'
      path: '/hot'
      fullPath: '/hot'
      preLoaderRoute: typeof HotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spirit': {
      id: '/spirit'
      path: '/spirit'
      fullPath: '/spirit'
      preLoaderRoute: typeof SpiritRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotRoute: HotRoute,
  SpiritRoute: SpiritRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
